### ISSUE TITLE
[CRASH] Sample + sample operation causes segfault

### ISSUE THREAD

**Issue by ZoomTen** [olive-editor/olive#1197]
**Commit Hash (8 character string of letters/numbers in title bar)**
27a4dbc8

**Platform**
Manjaro Linux 20.1, manual build

**Summary**
Given two audio sample nodes, attempting to perform a Math operation using the two nodes directly or via their Volume nodes will cause Olive to segfault.

**Steps to Reproduce**
1. Open Olive via `gdb olive-editor` and entering `run`.
2. Drag melody.wav and modulator.wav from the file manager into the project window
3. Drag melody.wav to the timeline window, creating a new 1080p sequence with a sample rate of 44.1khz (in mono)
4. Drag modulator.wav from the project window to the timeline window, placing it underneath melody.wav.
5. Right click on the node editor, Filter -> Show All.
6. Arrange the nodes to the following configuration (Alternatively, [the OVE file](https://cdn.discordapp.com/attachments/709964482427879441/756395641617252402/test.ove)):
![node setup](https://cdn.discordapp.com/attachments/709964482427879441/756395188041023498/image.png)
7. Connect the volume node above the node titled "modulator.wav" and connect it to the bottom parameter of the Math node.
8. UI freezes, obtain backtrace from the terminal window.

**Backtrace**
```
Thread 17 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa3bfe640 (LWP 2532594)]
0x00007ffff3647f60 in __memset_avx2_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff3647f60 in __memset_avx2_unaligned_erms () at /usr/lib/libc.so.6
#1  0x000055555575c9aa in olive::MathNodeBase::ValueInternal(olive::NodeValueDatabase&, olive::MathNodeBase::Operation, olive::MathNodeBase::Pairing, olive::NodeInput*, olive::NodeValue const&, olive::NodeInput*, olive::NodeValue const&) const (this=this@entry=0x555558d23550, value=..., operation=<optimized out>, 
    operation@entry=olive::MathNodeBase::kOpMultiply, pairing=pairing@entry=olive::MathNodeBase::kPairSampleSample, param_a_in=param_a_in@entry=0x555558d60a40, val_a=..., param_b_in=0x555558d5df80, val_b=...)
    at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:1324
#2  0x00005555557594d8 in olive::MathNode::Value(olive::NodeValueDatabase&) const (this=0x555558d23550, value=...) at /home/zumid/desktop/Apps/Olive Git/app/node/math/math/math.h:46
#3  0x000055555578098e in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) (this=0x5555593ca440, n=0x555558d23550, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:79
#4  0x0000555555780b11 in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) (this=0x5555593ca440, input=0x555558839d30, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:53
#5  0x0000555555780c14 in olive::NodeTraverser::GenerateDatabase(olive::Node const*, olive::TimeRange const&) (this=0x5555593ca440, node=0x555558840e30, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:41
#6  0x000055555578097b in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) (this=0x5555593ca440, n=0x555558840e30, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:76
#7  0x0000555555780b11 in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) (this=0x5555593ca440, input=0x555558840850, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:53
#8  0x0000555555780c14 in olive::NodeTraverser::GenerateDatabase(olive::Node const*, olive::TimeRange const&) (this=0x5555593ca440, node=0x55555883b8f0, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:41
#9  0x000055555578097b in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) (this=this@entry=0x5555593ca440, n=n@entry=0x55555883b8f0, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:76
#10 0x00005555557b0e35 in olive::RenderWorker::GenerateBlockTable(olive::TrackOutput const*, olive::TimeRange const&) (this=<optimized out>, track=<optimized out>, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/render/backend/renderworker.cpp:189
#11 0x000055555578093a in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) (this=0x5555593ca440, n=0x5555586e90b0, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:70
#12 0x0000555555780b11 in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) (this=this@entry=0x5555593ca440, input=0x5555588e0250, range=...)
    at /home/zumid/desktop/Apps/Olive Git/app/node/traverser.cpp:53
#13 0x00005555557ad10f in olive::RenderWorker::RenderAudio(std::shared_ptr<olive::RenderTicket>, olive::ViewerOutput*, olive::TimeRange const&)
    (this=0x5555593ca430, ticket=std::shared_ptr<olive::RenderTicket> (use count 6, weak count 0) = {...}, viewer=0x555557c3ded0, range=...) at /home/zumid/desktop/Apps/Olive Git/app/node/output/viewer/viewer.h:66
#14 0x00005555557a8954 in QtConcurrent::VoidStoredMemberFunctionPointerCall3<void, olive::RenderWorker, std::shared_ptr<olive::RenderTicket>, std::shared_ptr<olive::RenderTicket>, olive::ViewerOutput*, olive::ViewerOutput*, olive::TimeRange const&, olive::TimeRange>::runFunctor() (this=<optimized out>) at /usr/include/c++/10.2.0/ext/atomicity.h:100
#15 0x00005555557a7735 in non-virtual thunk to QtConcurrent::RunFunctionTask<void>::run() () at /usr/include/c++/10.2.0/bits/exception.h:63
#16 0x00007ffff3abae92 in  () at /usr/lib/libQt5Core.so.5
#17 0x00007ffff3ab6e0f in  () at /usr/lib/libQt5Core.so.5
#18 0x00007ffff4e493e9 in start_thread () at /usr/lib/libpthread.so.0
#19 0x00007ffff35e2293 in clone () at /usr/lib/libc.so.6
```
**Additional Information**
My goal is to use [modulator.wav](https://cdn.discordapp.com/attachments/709964482427879441/756392285909942312/modulator.wav) to control the volume of [melody.wav](https://cdn.discordapp.com/attachments/709964482427879441/756392288304889866/melody.wav), both mono, unsigned 8-bit WAV files. 

If the Math operation is performed using their respective Track nodes, it functions as expected.

I am using the following library versions to compile my copy of Olive 0.2:
      * `openimageio 2.1.18.1-2`
      * `opencolorio 1.1.1-4`
      * `openexr 2.5.3-1`
      * `qt5-base 5.15.0-4`
      * `ffmpeg-git 4.4.r99100.g6d71a25cc4-1`

**Comment by ThomasWilshaw** [comment]
This is the output I now get, does it look correct to you @ZoomTen ?

![image](https://user-images.githubusercontent.com/7781683/93717359-35275a80-fb6d-11ea-863a-6799d868361b.png)

**Comment by ThomasWilshaw** [comment]
f9af69c fixes this on my end.

**Comment by itsmattkc** [comment]
Yes f9af69c should fix this

**Comment by ZoomTen** [comment]
Confirmed fix, sample-sample as well as track-track operations work now. Thanks!
![image](https://user-images.githubusercontent.com/13794376/93729171-8c6d0f80-fbed-11ea-8fdb-ec440d7b037d.png)
