### ISSUE TITLE
[CRASH] Olive crashes after deleting sequence

### ISSUE THREAD

**Issue by Quackdoc** [olive-editor/olive#1436]
**7dd9115e** 

**Windows 10 64-Bit Ver. 2004 Build 19041** 

**Summary**
Olive will consistently crash after deleting a sequence a couple times (2 to 4 times) if you moved the play head to an uncached area, delete the clip from timeline, then delete the sequence

**Steps to Reproduce**

1. Import clip
2. Drag clip to timeline, allow sequence to be made from clip
3. move play head to uncached area
4. delete current clip
5. delete sequence
6. repeat until crash, consistent for me using provided video after 2-4 tries (AV1 encoded h0wever happens with x264 encoded video too)

<details><summary><strong>Backtrace</strong></summary><pre><code>

#0  0x00007fff179a89b0 in Qt5Core!?staticMetacallFunction@QMetaObjectBuilder@@QEBAP6AXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@ZXZ ()
   from C:\Program Files\Olive\Qt5Core.dll
#1  0x00007ff69ae3b5da in ?? ()

</code></pre></details>

**Additional Information**
Most consistent with this clip, although the clip is encoded in AV1 I have had the issues, albiet less consistent with x264 encoded footage as well

I thought at first it was related to #1255 however I dont touch the nodes

**Comment by itsmattkc** [comment]
Is this reproducible in the latest commit?

**Comment by itsmattkc** [comment]
Assuming this is fixed now, reply back if this is still an issue.
