### ISSUE TITLE
[CRASH] Crashed while opening projects with a video in it

### ISSUE THREAD

**Issue by yasharya2901** [olive-editor/olive#1456]
**Commit Hash** 
19eabf28

**Platform** 
Ubuntu 20.04 Linux 5.4.0-58-generic

**Summary**
When I tried to open a project which had a video, the app crashes. I tried saving a file with a solid color and reopened it successfully, but I couldn't do the same with a newly created project with a video in it and neither can open the previous projects with a video in it.

**Steps to Reproduce**

1. Go to Open Project
2. Choose the file and hit open. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

[WARNING] Trying to use locale "en_IN" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/home/yash/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.12.8 ((null):0)
[DEBUG] Using graphics driver: NVIDIA Corporation ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1b.0.analog-stereo" ((null):0)
[4612:4612:20210103,174846.649106:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649183:ERROR process_reader_linux.cc:520] no module mappings 0x7f735071e000
[4612:4612:20210103,174846.649247:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649260:ERROR process_reader_linux.cc:520] no module mappings 0x7f7350606000
[4612:4612:20210103,174846.649399:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649412:ERROR process_reader_linux.cc:520] no module mappings 0x7f7350548000
[4612:4612:20210103,174846.649550:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649564:ERROR process_reader_linux.cc:520] no module mappings 0x7f7350494000
[4612:4612:20210103,174846.649615:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649628:ERROR process_reader_linux.cc:520] no module mappings 0x7f7350380000
[4612:4612:20210103,174846.649774:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649787:ERROR process_reader_linux.cc:520] no module mappings 0x7f734ec5f000
[4612:4612:20210103,174846.649837:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649849:ERROR process_reader_linux.cc:520] no module mappings 0x7f734e937000
[4612:4612:20210103,174846.649898:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649913:ERROR process_reader_linux.cc:520] no module mappings 0x7f734e8ab000
[4612:4612:20210103,174846.649949:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.649957:ERROR process_reader_linux.cc:520] no module mappings 0x7f734e7f6000
[4612:4612:20210103,174846.650950:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.650965:ERROR process_reader_linux.cc:520] no module mappings 0x7f734d11e000
[4612:4612:20210103,174846.650994:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.651001:ERROR process_reader_linux.cc:520] no module mappings 0x7f734cefe000
[4612:4612:20210103,174846.651028:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.651035:ERROR process_reader_linux.cc:520] no module mappings 0x7f734c842000
[4612:4612:20210103,174846.651928:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.651947:ERROR process_reader_linux.cc:520] no module mappings 0x7f734b110000
[4612:4612:20210103,174846.652035:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652043:ERROR process_reader_linux.cc:520] no module mappings 0x7f734abd2000
[4612:4612:20210103,174846.652067:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652074:ERROR process_reader_linux.cc:520] no module mappings 0x7f734ab3e000
[4612:4612:20210103,174846.652100:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652107:ERROR process_reader_linux.cc:520] no module mappings 0x7f734aac4000
[4612:4612:20210103,174846.652198:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652205:ERROR process_reader_linux.cc:520] no module mappings 0x7f734aa27000
[4612:4612:20210103,174846.652414:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652430:ERROR process_reader_linux.cc:520] no module mappings 0x7f734a920000
[4612:4612:20210103,174846.652461:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652468:ERROR process_reader_linux.cc:520] no module mappings 0x7f734a8af000
[4612:4612:20210103,174846.652494:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652501:ERROR process_reader_linux.cc:520] no module mappings 0x7f734a57d000
[4612:4612:20210103,174846.652527:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652533:ERROR process_reader_linux.cc:520] no module mappings 0x7f734a008000
[4612:4612:20210103,174846.652616:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.652623:ERROR process_reader_linux.cc:520] no module mappings 0x7f7349ce5000
[4612:4612:20210103,174846.653184:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653202:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348dba000
[4612:4612:20210103,174846.653246:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653258:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348d8b000
[4612:4612:20210103,174846.653300:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653312:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348d7a000
[4612:4612:20210103,174846.653352:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653363:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348d2f000
[4612:4612:20210103,174846.653405:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653417:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348d0b000
[4612:4612:20210103,174846.653458:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.653470:ERROR process_reader_linux.cc:520] no module mappings 0x7f7348cf6000
[4612:4612:20210103,174846.654821:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.654849:ERROR process_reader_linux.cc:520] no module mappings 0x7f734638f000
[4612:4612:20210103,174846.657216:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.657244:ERROR process_reader_linux.cc:520] no module mappings 0x7f735053e000
[4612:4612:20210103,174846.657282:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.657297:ERROR process_reader_linux.cc:520] no module mappings 0x7f7342ae3000
[4612:4612:20210103,174846.657431:ERROR elf_image_reader.cc:95] out of order load segments
[4612:4612:20210103,174846.657448:ERROR process_reader_linux.cc:520] no module mappings 0x7f73428f7000
[4612:4612:20210103,174846.658103:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658127:ERROR process_reader_linux.cc:520] no module mappings 0x7f73417b8000
[4612:4612:20210103,174846.658165:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658181:ERROR process_reader_linux.cc:520] no module mappings 0x7f734295e000
[4612:4612:20210103,174846.658546:ERROR elf_image_reader.cc:622] no dynamic segment
[4612:4612:20210103,174846.658566:ERROR process_reader_linux.cc:520] no module mappings 0x7f733838a000
[4612:4612:20210103,174846.658601:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658615:ERROR process_reader_linux.cc:520] no module mappings 0x7f733837f000
[4612:4612:20210103,174846.658650:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658667:ERROR process_reader_linux.cc:520] no module mappings 0x7f7338371000
[4612:4612:20210103,174846.658703:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658716:ERROR process_reader_linux.cc:520] no module mappings 0x7f7338365000
[4612:4612:20210103,174846.658751:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658765:ERROR process_reader_linux.cc:520] no module mappings 0x7f7338357000
[4612:4612:20210103,174846.658888:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658905:ERROR process_reader_linux.cc:520] no module mappings 0x7f73380d5000
[4612:4612:20210103,174846.658949:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.658964:ERROR process_reader_linux.cc:520] no module mappings 0x7f73380cc000
[4612:4612:20210103,174846.659000:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659016:ERROR process_reader_linux.cc:520] no module mappings 0x7f73380c3000
[4612:4612:20210103,174846.659050:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659065:ERROR process_reader_linux.cc:520] no module mappings 0x7f73380b7000
[4612:4612:20210103,174846.659100:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659116:ERROR process_reader_linux.cc:520] no module mappings 0x7f73380ae000
[4612:4612:20210103,174846.659151:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659166:ERROR process_reader_linux.cc:520] no module mappings 0x7f7338027000
[4612:4612:20210103,174846.659391:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659420:ERROR process_reader_linux.cc:520] no module mappings 0x7f73388ed000
[4612:4612:20210103,174846.659454:ERROR elf_image_reader.cc:116] no preferred header address
[4612:4612:20210103,174846.659468:ERROR process_reader_linux.cc:520] no module mappings 0x7f73200ff000
/tmp/.mount_Olive-uGkVDb/usr/bin/olive-crashhandler: symbol lookup error: /tmp/.mount_Olive-uGkVDb/usr/plugins/platforms/../../lib/libQt5DBus.so.5: undefined symbol: _ZdlPvm, version Qt_5
Segmentation fault (core dumped)

</code></pre></details>

**Additional Information**

**Comment by tokc** [comment]
I experience the same issue on Manjaro (Arch, btw), so I'll add my own report as an additional datapoint.

**Commit Hash**
19eabf28


**Platform**
Linux 5.9.11-3-MANJARO #1 SMP PREEMPT


**Summary**
Olive crashes upon trying to open a previously saved project that contains videos in the timeline.
I am using the appimage version of Olive downloaded from the Olive website.

**Steps to Reproduce**

1. Run Olive.
2. Add a video file to the "Project" pane.
3. Drag the video from the "Project" pane to the sequence.
4. Choose automatic sequence properties.
5. Save the project.
6. Exit Olive.
7. Run Olive.
8. Click File > Open Project.
9. Locate the .ove file created in step 5.
10. Click "Open".
- Expected behaviour: Project opens.
- Observed behaviour: Olive segfaults.

<details><summary><strong>Backtrace</strong></summary><pre><code>
[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/home/elaine/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.12.8 ((null):0)
[DEBUG] Using graphics driver: X.Org ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_0c_00.3.analog-stereo" ((null):0)
[217184:217184:20210103,134714.917059:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917135:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e36d6d000
[217184:217184:20210103,134714.917192:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917201:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e36c55000
[217184:217184:20210103,134714.917367:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917376:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e36b97000
[217184:217184:20210103,134714.917515:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917529:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e36ac9000
[217184:217184:20210103,134714.917577:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917585:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e369b5000
[217184:217184:20210103,134714.917740:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917751:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e35294000
[217184:217184:20210103,134714.917798:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917808:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e34f6c000
[217184:217184:20210103,134714.917853:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917862:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e34ee0000
[217184:217184:20210103,134714.917906:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.917914:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e34e2b000
[217184:217184:20210103,134714.919169:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.919180:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e33756000
[217184:217184:20210103,134714.919222:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.919231:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e33536000
[217184:217184:20210103,134714.919272:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.919281:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e32e7a000
/tmp/.mount_Olive-eCGRCR/usr/bin/olive-crashhandler: symbol lookup error: /tmp/.mount_Olive-eCGRCR/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API
[217184:217184:20210103,134714.920340:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920351:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e31776000
[217184:217184:20210103,134714.920492:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920501:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e31238000
[217184:217184:20210103,134714.920540:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920548:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e311a4000
[217184:217184:20210103,134714.920588:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920596:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e3112a000
[217184:217184:20210103,134714.920728:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920737:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e3108d000
[217184:217184:20210103,134714.920954:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.920964:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e30f86000
[217184:217184:20210103,134714.921003:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921012:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e30f15000
[217184:217184:20210103,134714.921050:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921058:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e30be3000
[217184:217184:20210103,134714.921097:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921105:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e3066e000
[217184:217184:20210103,134714.921236:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921245:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e3034b000
[217184:217184:20210103,134714.921929:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921940:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f40b000
[217184:217184:20210103,134714.921977:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.921986:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f3dc000
[217184:217184:20210103,134714.922022:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.922031:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f3cb000
[217184:217184:20210103,134714.922067:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.922075:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f380000
[217184:217184:20210103,134714.922111:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.922119:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f35c000
[217184:217184:20210103,134714.922154:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.922163:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2f347000
[217184:217184:20210103,134714.923295:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.923306:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2ca13000
[217184:217184:20210103,134714.926101:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.926114:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e36b8d000
[217184:217184:20210103,134714.926143:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.926151:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2939a000
[217184:217184:20210103,134714.926252:ERROR elf_image_reader.cc:95] out of order load segments
[217184:217184:20210103,134714.926261:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2918e000
[217184:217184:20210103,134714.926849:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.926860:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2921a000
[217184:217184:20210103,134714.926888:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.926896:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e291f8000
[217184:217184:20210103,134714.928890:ERROR elf_image_reader.cc:622] no dynamic segment
[217184:217184:20210103,134714.928908:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e28042000
[217184:217184:20210103,134714.928932:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.928940:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2002a000
[217184:217184:20210103,134714.928963:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.928971:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e2001c000
[217184:217184:20210103,134714.928993:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929000:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e20010000
[217184:217184:20210103,134714.929026:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929034:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e28038000
[217184:217184:20210103,134714.929138:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929147:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e08210000
[217184:217184:20210103,134714.929168:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929176:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e08207000
[217184:217184:20210103,134714.929197:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929205:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e081fe000
[217184:217184:20210103,134714.929226:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929234:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e081f2000
[217184:217184:20210103,134714.929255:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929263:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e081e9000
[217184:217184:20210103,134714.929284:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929292:ERROR process_reader_linux.cc:520] no module mappings 0x7f3e08162000
[217184:217184:20210103,134714.929386:ERROR elf_image_reader.cc:116] no preferred header address
[217184:217184:20210103,134714.929395:ERROR process_reader_linux.cc:520] no module mappings 0x7f3de80da000
Segmentation fault (core dumped)
</code></pre></details>

**Additional Information**
Does not happen in 0ac9dd9. But I assume the codebase is significantly different between 0.1 and 0.2.

Files used to reproduce the crash: [olive_test.zip](https://drive.google.com/file/d/1x0rMNXczNEiIzhOKYlH8waWfKvNDGb-6/view?usp=sharing)

**Comment by Corvus69** [comment]
Exact same reproducible crash to desktop for me - I'm using:

Linux Mint 20 Cinnamon
Cinnamon Version 4.6.7
Linux Kernel 5.4.0-60-generic
Processor: Intel Core 2 Extreme CPU X9650 @ 3.6GHz x 4
Memory: 7.7 GiB
Hard Drives: 1502.8 GB
GPU: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]

If it's any use, the bt output was as follows:

(gdb) bt
#0  0x0000000000651e12 in olive::NodeTraverser::PostProcessTable (this=0x7fffceffc3f0, node=0x7fffc4045540, range=..., output_params=...)
    at ../app/node/traverser.cpp:194
#1  0x0000000000652e7d in olive::NodeTraverser::GenerateTable (this=0x7fffceffc3f0, n=0x7fffc4045540, range=...) at ../app/node/traverser.cpp:81
#2  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffceffc3f0, input=0x7fffc4022970, range=...) at ../app/node/traverser.cpp:53
#3  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffceffc3f0, node=0x7fffc4083170, range=...)
    at ../app/node/traverser.cpp:41
#4  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffceffc3f0, n=0x7fffc4083170, range=...) at ../app/node/traverser.cpp:76
#5  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffceffc3f0, input=0x7fffc402ce70, range=...) at ../app/node/traverser.cpp:53
#6  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffceffc3f0, node=0x7fffc40a6ab0, range=...)
    at ../app/node/traverser.cpp:41
#7  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffceffc3f0, n=0x7fffc40a6ab0, range=...) at ../app/node/traverser.cpp:76
#8  0x00000000006535f0 in olive::NodeTraverser::GenerateBlockTable (this=0x7fffceffc3f0, track=<optimised out>, range=...)
    at ../app/node/traverser.cpp:99
#9  0x0000000000652e2d in olive::NodeTraverser::GenerateTable (this=0x7fffceffc3f0, n=0x7fffc40a0dc0, range=...) at ../app/node/traverser.cpp:70
#10 0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffceffc3f0, input=0x7fffc4064bf0, range=...) at ../app/node/traverser.cpp:53
#11 0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffceffc3f0, node=0x7fffc4083e50, range=...)
    at ../app/node/traverser.cpp:41
#12 0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffceffc3f0, n=0x7fffc4083e50, range=...) at ../app/node/traverser.cpp:76
#13 0x0000000000653586 in olive::NodeTraverser::GenerateTable (this=this@entry=0x7fffceffc3f0, n=0x7fffc4083e50, in=..., out=...)
    at ../app/node/traverser.cpp:88
#14 0x000000000062b7f2 in olive::ViewerOutput::VerifyLength (this=0x7fffc4067910) at ../app/common/rational.h:40
#15 0x000000000062f250 in olive::ViewerOutput::InvalidateCache (this=0x7fffc4067910, range=..., from=0x7fffc40201b0, source=0x7fffc40201b0)
    at ../app/node/output/viewer/viewer.cpp:133
#16 0x0000000000647171 in olive::Node::InputConnectionChanged (this=0x7fffc4067910, edge=...) at ../app/node/node.cpp:208
#17 0x000000000064b7b3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void, void (olive::Node::*)(std::shared_ptr<olive::NodeEdge>)>::call (arg=<optimised out>, o=<optimised out>, f=<optimised out>)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/atomicity.h:96
#18 QtPrivate::FunctionPointer<void (olive::Node::*)(std::shared_ptr<olive::NodeEdge>)>::call<QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void> (arg=<optimised out>, o=<optimised out>, f=<optimised out>) at /usr/local/include/QtCore/qobjectdefs_impl.h:185
#19 QtPrivate::QSlotObject<void (olive::Node::*)(std::shared_ptr<olive::NodeEdge>), QtPrivate::List<std::shared_ptr<olive::NodeEdge> >, void>::impl (
    which=<optimised out>, this_=<optimised out>, r=<optimised out>, a=<optimised out>, ret=<optimised out>)
    at /usr/local/include/QtCore/qobjectdefs_impl.h:414
#20 0x00007ffff37efe95 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_Olive-d12nlf/usr/bin/../lib/libQt5Core.so.5
#21 0x000000000055f6e2 in olive::NodeParam::EdgeAdded (this=this@entry=0x7fffc40201b0, 
    _t1=std::shared_ptr<olive::NodeEdge> (use count 5, weak count 0) = {...}) at app/olive-editor_autogen/MFLS3X56JO/moc_param.cpp:144
#22 0x000000000064f010 in olive::NodeParam::ConnectEdge (output=output@entry=0x7fffc40648f0, input=0x7fffc40201b0)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/atomicity.h:96
#23 0x00000000005bc90f in olive::XMLConnectNodes (xml_node_data=..., command=command@entry=0x0) at ../app/common/xmlutils.cpp:38
#24 0x0000000000661130 in olive::Sequence::Load (this=0x7fffc4072280, reader=0x7fffceffcb28, xml_node_data=..., version=201122, 
    cancelled=0x7fff9800ddb8) at ../app/project/item/sequence/sequence.cpp:170
#25 0x000000000065b1d9 in olive::Folder::Load (this=this@entry=0x7fffc40a84a0, reader=reader@entry=0x7fffceffcb28, xml_node_data=..., 
    version=version@entry=201122, cancelled=cancelled@entry=0x7fff9800ddb8) at ../app/project/item/folder/folder.cpp:78
#26 0x000000000066436e in olive::Project::Load (this=0x7fffc40a8490, reader=0x7fffceffcb28, layout=0x7fff9800dde0, version=201122, 
    cancelled=0x7fff9800ddb8) at ../app/project/project.cpp:53
#27 0x00000000006a6688 in olive::ProjectLoadTask::Run (this=0x7fff9800dda0) at ../app/common/cancelableobject.h:45
--Type <RET> for more, q to quit, c to continue without paging--c
#28 0x00000000005f2e6f in non-virtual thunk to QtConcurrent::RunFunctionTask<bool>::run() () at /usr/local/include/QtCore/qarraydata.h:236
#29 0x00007ffff360bac2 in ?? () from /tmp/.mount_Olive-d12nlf/usr/bin/../lib/libQt5Core.so.5
#30 0x00007ffff36087d3 in ?? () from /tmp/.mount_Olive-d12nlf/usr/bin/../lib/libQt5Core.so.5
#31 0x00007ffff4ba8609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#32 0x00007ffff312f293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 

A short video:
https://user-images.githubusercontent.com/47607762/104136990-81531080-5391-11eb-9538-b5fba955fd2c.mp4

**Comment by itsmattkc** [comment]
Can you test this with a new project file on the latest commit?

**Comment by Corvus69** [comment]
> Can you test this with a new project file on the latest commit?

Hello - I can happily confirm that I can now load and save projects with no (yet observed) problems using commit 0a17e0fb. I'll check the latest (5b04d84b) and report back. Many thanks! Dave.

**Comment by Corvus69** [comment]
> Can you test this with a new project file on the latest commit?

Well, I've tried it with the latest nightly build (5b04d84b) and it seems to work fine. (Though older projects are somewhat incompatible). I see you also fixed the CTD bug if you grab the sequence viewer window when something was on the timeline - awesome! Many thanks for all your hard work! Dave.

**Comment by tokc** [comment]
Appears to work as expected in the 7e00ffa8 AppImage.

**Comment by itsmattkc** [comment]
I will close this for now. Anyone affected by this can feel free to reply back if this issue resurfaces.
