### ISSUE TITLE
[CRASH] Timeline Drag&Drop

### ISSUE THREAD

**Issue by jkroll20** [olive-editor/olive#1493]
**Commit Hash** 
19eabf28

**Platform** 
Debian bullseye/sid

**Summary**
Crash when dropping a clip into the timeline

**Steps to Reproduce**

1. open olive
2. add a clip
3. drag the clip into the timeline
4. in the popup, select "automatically select parameters from footage" or "set parameters manually" (doesn't matter)

<details><summary><strong>Backtrace</strong></summary><pre><code>

Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
olive::Project::is_modified (this=0x0) at /home/sachzwang/src/olive/app/project/project.cpp:171
171	  return is_modified_;
(gdb) bt
#0  olive::Project::is_modified() const (this=0x0) at /home/sachzwang/src/olive/app/project/project.cpp:171
#1  0x00005555557d589e in olive::UndoCommand::redo() (this=0x555558acb750) at /home/sachzwang/src/olive/app/undo/undocommand.cpp:36
#2  0x00007ffff4866e42 in QUndoCommand::redo() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff4869276 in QUndoStack::push(QUndoCommand*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x0000555555829715 in olive::ImportTool::DropGhosts(bool) (this=0x5555587b7560, insert=<optimized out>) at /home/sachzwang/src/olive/app/widget/timelinewidget/tool/import.cpp:491
#5  0x0000555555829f11 in olive::ImportTool::DragDrop(olive::TimelineViewMouseEvent*) (event=0x7fffffffb9a0, this=0x5555587b7560) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:69
#6  olive::ImportTool::DragDrop(olive::TimelineViewMouseEvent*) (this=0x5555587b7560, event=0x7fffffffb9a0) at /home/sachzwang/src/olive/app/widget/timelinewidget/tool/import.cpp:184
#7  0x00005555558421b5 in olive::TimelineWidget::ViewDragDropped(olive::TimelineViewMouseEvent*) (this=0x55555823eb70, event=<optimized out>) at /home/sachzwang/src/olive/app/widget/timelinewidget/timelinewidget.cpp:876
#8  0x00007ffff3a5b4e6 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00005555556d4ea2 in olive::TimelineView::DragDropped(olive::TimelineViewMouseEvent*) (this=this@entry=0x5555589c3e80, _t1=<optimized out>, _t1@entry=0x7fffffffb9a0)
    at /home/sachzwang/src/olive/build/app/olive-editor_autogen/EYCRI7KD7O/moc_timelineview.cpp:264
#10 0x000055555583c42a in olive::TimelineView::dropEvent(QDropEvent*) (this=0x5555589c3e80, event=0x7fffffffbdb0) at /home/sachzwang/src/olive/app/widget/timelinewidget/view/timelineview.cpp:199
#11 0x00007ffff4527f9e in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff45d041e in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff3a24c73 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff44e814e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff44f0f31 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff3a24f0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff4542742 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff4543573 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff44e815f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff3a24f0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff3e0054f in QGuiApplicationPrivate::processDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#22 0x00007ffff3dd3ec8 in QWindowSystemInterface::handleDrop(QWindow*, QMimeData const*, QPoint const&, QFlags<Qt::DropAction>, QFlags<Qt::MouseButton>, QFlags<Qt::KeyboardModifier>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#23 0x00007fff602a41a8 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#24 0x00007fff602a815e in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#25 0x00007ffff3e3e65d in QBasicDrag::eventFilter(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007ffff3a24b46 in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff44e8198 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff3a24f0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff3dfe583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#30 0x00007ffff3dd464c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007fff602947da in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#32 0x00007ffff1dade6b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff1dae118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff1dae1cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#35 0x00007ffff3a7c45f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff3a238cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff3e3d7a3 in QBasicDrag::drag(QDrag*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007ffff3e3aaa5 in QDragManager::drag(QDrag*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#39 0x00007ffff3e3adcb in QDrag::exec(QFlags<Qt::DropAction>, Qt::DropAction) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007ffff474b5f1 in QAbstractItemView::startDrag(QFlags<Qt::DropAction>) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff4749ecd in QAbstractItemView::mouseMoveEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff4527f9e in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#43 0x00007ffff45d041e in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#44 0x00007ffff3a24c73 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007ffff44e814e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#46 0x00007ffff44ef04b in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#47 0x00007ffff3a24f0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#48 0x00007ffff44ee076 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007ffff4540001 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00007ffff454332e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#51 0x00007ffff44e815f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#52 0x00007ffff3a24f0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#53 0x00007ffff3dfe583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#54 0x00007ffff3dd464c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#55 0x00007fff602947da in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#56 0x00007ffff1dade6b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#57 0x00007ffff1dae118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007ffff1dae1cf in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff3a7c45f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#60 0x00007ffff3a238cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#61 0x00007ffff3a2bb40 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00005555556ca678 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffd878) at /home/sachzwang/src/olive/app/main.cpp:184
(gdb) 

</code></pre></details>

**Additional Information**

Clip I'm trying to add is from a phone, h264 codec. Haven't tried any other media yet. 
<details><summary>ffprobe output of clip</summary><pre>ffprobe version 4.3.1-8 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=8 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'VID_20210220_171257.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-02-20T16:13:03.000000Z
    com.android.version: 9
    com.android.manufacturer: Motorola
    com.android.model: Moto X4
  Duration: 00:00:05.09, start: 0.000000, bitrate: 16764 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/smpte170m), 2592x1944, 16030 kb/s, SAR 1:1 DAR 4:3, 28.71 fps, 29.92 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2021-02-20T16:13:03.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2021-02-20T16:13:03.000000Z
      handler_name    : SoundHandle
</pre></details>

**Comment by jkroll20** [comment]
I'm not sure what happened, but I can't reproduce the crash anymore when adding the same clip to a new project. I can reproduce it every time with the project file I saved before. Maybe the file is corrupt?


[privileg6000-dokumentation.ove.txt](https://github.com/olive-editor/olive/files/6016254/privileg6000-dokumentation.ove.txt)

**Comment by itsmattkc** [comment]
Can you test this with a new project file on the latest commit?

**Comment by itsmattkc** [comment]
Closing due to inactivity. Reply back if this issue can still be recreated.
