### ISSUE TITLE
[CRASH] Undoing audio node in nodeview causes crash

### ISSUE THREAD

**Issue by parona-source** [olive-editor/olive#1523]
**Commit Hash** 
cd6544ba

**Platform** 
Gentoo (Portage 3.0.13 (python 3.9.1-final-0, default/linux/amd64/17.1/desktop, gcc-10.2.0, glibc-2.32-r7, 5.11.6-xanmod1 x86_64))

**Summary**
Undoing audio node in nodeview crashes program. First got this from self compiled version, then was able to reproduce in appimage. Ive tried with mp4, webm and mkv on the AppImage. There is one webm that i havent been able to get it to happen otherwise it gets triggered everytime.

**Steps to Reproduce**

1. Import video
1. Put video in timeline with automatically set presets 
2. In nodeview undo audio node

<details><summary><strong>Backtrace</strong></summary><pre><code>

Backtrace from AppImage 0.2.0-cd6544ba when run under gdb.
```
Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
QVector<QWidget*>::QVector (this=0x7fffffffb990, v=...) at /usr/local/include/QtCore/qvector.h:359
359     /usr/local/include/QtCore/qvector.h: No such file or directory.
(gdb) bt
#0  QVector<QWidget*>::QVector (this=0x7fffffffb990, v=...) at /usr/local/include/QtCore/qvector.h:359
#1  0x00000000006e95a5 in QtPrivate::QForeachContainer<QVector<QWidget*> >::QForeachContainer (t=..., this=0x7fffffffb990) at /usr/local/include/QtCore/qglobal.h:976
#2  QtPrivate::qMakeForeachContainer<QVector<QWidget*> const&> (t=...) at /usr/local/include/QtCore/qglobal.h:1004
#3  olive::NodeParamViewItemBody::UpdateUIForEdgeConnection (this=0x3846cc0, input=...) at ../app/widget/nodeparamview/nodeparamviewitem.cpp:402
#4  0x00007ffff37dce95 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#5  0x000000000055987a in olive::Node::InputDisconnected (this=<optimized out>, _t1=..., _t2=...) at app/olive-editor_autogen/MFLS3X56JO/moc_node.cpp:460
#6  0x000000000062c042 in olive::Node::DisconnectEdge (output=..., input=...) at ../app/node/param.h:133
#7  0x000000000062ee45 in olive::Node::InputArrayRemove (this=this@entry=0x3b19070, id=..., index=0, undoable=undoable@entry=false) at ../app/node/node.cpp:942
#8  0x000000000061c22d in olive::Track::RippleRemoveBlock (this=this@entry=0x3b19070, block=0x3909f10) at ../app/node/output/track/track.cpp:517
#9  0x000000000072072b in olive::TrackPlaceBlockCommand::undo (this=0x38e1c90) at ../app/widget/timelinewidget/timelineundo.h:1564
#10 0x00000000006c509a in olive::UndoCommand::undo_and_set_modified (this=0x38e1c90) at ../app/undo/undocommand.cpp:54
#11 0x00000000006c50e5 in olive::MultiUndoCommand::undo (this=0x3059ed0) at ../app/undo/undocommand.cpp:37
#12 0x00000000006c509a in olive::UndoCommand::undo_and_set_modified (this=0x3059ed0) at ../app/undo/undocommand.cpp:54
#13 0x00000000006c599e in olive::UndoStack::undo (this=0x7fffffffdb18) at ../app/undo/undostack.cpp:81
#14 olive::UndoStack::undo (this=0x7fffffffdb18) at ../app/undo/undostack.cpp:77
#15 0x00007ffff37dce95 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#16 0x00007ffff42756d2 in QAction::triggered(bool) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff4277af2 in QAction::activate(QAction::ActionEvent) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff43ec5a2 in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff43f377a in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff43f4742 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff42ba836 in QWidget::event(QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff43f6c7b in QMenu::event(QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff427b5f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#24 0x00007ffff4284808 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#25 0x00007ffff37b3692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#26 0x00007ffff4283a80 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff42d6080 in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff42d83cc in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff427b5f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff42846a0 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#31 0x00007ffff37b3692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#32 0x00007ffff3c2d6b3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#33 0x00007ffff3c2ef22 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#34 0x00007ffff3c0af7b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#35 0x00007fffea486c7a in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#36 0x00007ffff2a6376b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#37 0x00007ffff2acd0a2 in ?? () from /usr/lib64/libglib-2.0.so.0
#38 0x00007ffff2a5efd1 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#39 0x00007ffff3806811 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#40 0x00007ffff37b247b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#41 0x00007ffff43f159d in QMenu::exec(QPoint const&, QAction*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#42 0x00000000006f9603 in olive::NodeView::ShowContextMenu (this=0x306e080, pos=...) at ../app/widget/nodeview/nodeview.cpp:723
#43 0x00007ffff37dce95 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#44 0x00007ffff42a2165 in QWidget::customContextMenuRequested(QPoint const&) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#45 0x00007ffff42bb4d6 in QWidget::event(QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#46 0x00007ffff43639be in QFrame::event(QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#47 0x00007ffff45a679c in QGraphicsView::viewportEvent(QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#48 0x00007ffff37b33b3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#49 0x00007ffff427b5e1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#50 0x00007ffff42856d3 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#51 0x00007ffff37b3692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#52 0x00007ffff42d5cda in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#53 0x00007ffff42d83cc in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#54 0x00007ffff427b5f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#55 0x00007ffff42846a0 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Widgets.so.5
#56 0x00007ffff37b3692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#57 0x00007ffff3c2d6b3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#58 0x00007ffff3c2ef22 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#59 0x00007ffff3c0af7b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Gui.so.5
#60 0x00007fffea486c7a in ?? () from /tmp/.mount_Olive-oJ1UO5/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#61 0x00007ffff2a6376b in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#62 0x00007ffff2acd0a2 in ?? () from /usr/lib64/libglib-2.0.so.0
#63 0x00007ffff2a5efd1 in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#64 0x00007ffff3806811 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#65 0x00007ffff37b247b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#66 0x00007ffff37b9a6e in QCoreApplication::exec() () from /tmp/.mount_Olive-oJ1UO5/usr/bin/../lib/libQt5Core.so.5
#67 0x0000000000551451 in main (argc=<optimized out>, argv=0x7fffffffdcb8) at ../app/main.cpp:184
```

Backtrace from self compiled olive 0.2.0-cd6544ba with debug symbols spitted and flags "-O2 -pipe -ggdb"
```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
QVector<QWidget*>::QVector (this=0x7fffffffbc20, v=...) at /usr/include/qt5/QtCore/qvector.h:379
379         if (v.d->ref.ref()) {
(gdb) bt
#0  QVector<QWidget*>::QVector(QVector<QWidget*> const&) (this=0x7fffffffbc20, v=...) at /usr/include/qt5/QtCore/qvector.h:379
#1  0x00005555557f95b3 in QtPrivate::QForeachContainer<QVector<QWidget*> >::QForeachContainer(QVector<QWidget*> const&) (t=<optimized out>, this=0x7fffffffbc20) at /usr/include/qt5/QtCore/qglobal.h:1064
#2  QtPrivate::qMakeForeachContainer<QVector<QWidget*> const&>(QVector<QWidget*> const&) (t=<optimized out>) at /usr/include/qt5/QtCore/qglobal.h:1092
#3  olive::NodeParamViewItemBody::UpdateUIForEdgeConnection(olive::NodeInput const&) (this=0x55555996b700, input=...) at /usr/src/debug/media-video/olive-9999/olive-9999/app/widget/nodeparamview/nodeparamviewitem.cpp:402
#4  0x00007ffff39d7e3d in  () at /usr/lib64/libQt5Core.so.5
#5  0x00005555556c7a6a in olive::Node::InputDisconnected(olive::NodeOutput const&, olive::NodeInput const&) (this=<optimized out>, _t1=..., _t2=...) at app/olive-editor_autogen/MFLS3X56JO/moc_node.cpp:461
#6  0x000055555576ce34 in olive::Node::DisconnectEdge(olive::NodeOutput const&, olive::NodeInput const&) (output=..., input=...) at /usr/src/debug/media-video/olive-9999/olive-9999/app/node/param.h:133
#7  0x00005555557785c5 in olive::Node::InputArrayRemove(QString const&, int, bool) (this=0x555558941e20, id=..., index=0, undoable=<optimized out>) at /usr/src/debug/media-video/olive-9999/olive-9999/app/node/node.cpp:942
#8  0x0000555555763b1b in olive::Track::RippleRemoveBlock(olive::Block*) (this=this@entry=0x555558941e20, block=0x555558310760) at /usr/src/debug/media-video/olive-9999/olive-9999/app/node/output/track/track.cpp:517
#9  0x000055555582ae8b in olive::TrackPlaceBlockCommand::undo() (this=0x555558918a50) at /usr/src/debug/media-video/olive-9999/olive-9999/app/widget/timelinewidget/timelineundo.h:1564
#10 0x00005555557d72ea in olive::UndoCommand::undo_and_set_modified() (this=0x555558918a50) at /usr/src/debug/media-video/olive-9999/olive-9999/app/undo/undocommand.cpp:54
#11 0x00005555557d7335 in olive::MultiUndoCommand::undo() (this=0x55555838f0b0) at /usr/src/debug/media-video/olive-9999/olive-9999/app/undo/undocommand.cpp:37
#12 0x00005555557d72ea in olive::UndoCommand::undo_and_set_modified() (this=0x55555838f0b0) at /usr/src/debug/media-video/olive-9999/olive-9999/app/undo/undocommand.cpp:54
#13 0x00005555557d78be in olive::UndoStack::undo() (this=0x7fffffffdbe8) at /usr/src/debug/media-video/olive-9999/olive-9999/app/undo/undostack.cpp:81
#14 olive::UndoStack::undo() (this=0x7fffffffdbe8) at /usr/src/debug/media-video/olive-9999/olive-9999/app/undo/undostack.cpp:77
#15 0x00007ffff39d7e3d in  () at /usr/lib64/libQt5Core.so.5
#16 0x00007ffff44657dc in QAction::activate(QAction::ActionEvent) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff45fbbca in  () at /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff45fef4a in  () at /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff44afabc in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff446dcc5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff44707a8 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff399e918 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#23 0x00007ffff446f776 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib64/libQt5Widgets.so.5
#24 0x00007ffff44cdff3 in  () at /usr/lib64/libQt5Widgets.so.5
#25 0x00007ffff446dcc5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#26 0x00007ffff399e918 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#27 0x00007ffff3dad4d5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#28 0x00007ffff3d933cb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#29 0x00007fffebd430ea in  () at /usr/lib64/libQt5XcbQpa.so.5
#30 0x00007ffff1d7876b in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#31 0x00007ffff1de20a2 in  () at /usr/lib64/libglib-2.0.so.0
#32 0x00007ffff1d73fd1 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#33 0x00007ffff39ecea0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#34 0x00007ffff399d856 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#35 0x00007ffff4602b1d in  () at /usr/lib64/libQt5Widgets.so.5
#36 0x00007ffff4602c3f in QMenu::exec(QPoint const&, QAction*) () at /usr/lib64/libQt5Widgets.so.5
#37 0x000055555580846b in olive::NodeView::ShowContextMenu(QPoint const&) (this=0x555558124140, pos=...) at /usr/src/debug/media-video/olive-9999/olive-9999/app/widget/nodeview/nodeview.cpp:723
#38 0x00007ffff39d7e3d in  () at /usr/lib64/libQt5Core.so.5
#39 0x00007ffff44aff3d in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#40 0x00007ffff45534ce in QFrame::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#41 0x00007ffff39a4412 in  () at /usr/lib64/libQt5Core.so.5
#42 0x00007ffff446dcb4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#43 0x00007ffff44712b5 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#44 0x00007ffff399e918 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#45 0x00007ffff44cc947 in  () at /usr/lib64/libQt5Widgets.so.5
#46 0x00007ffff446dcc5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#47 0x00007ffff399e918 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#48 0x00007ffff3dad4d5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#49 0x00007ffff3d933cb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#50 0x00007fffebd430ea in  () at /usr/lib64/libQt5XcbQpa.so.5
#51 0x00007ffff1d7876b in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#52 0x00007ffff1de20a2 in  () at /usr/lib64/libglib-2.0.so.0
#53 0x00007ffff1d73fd1 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#54 0x00007ffff39ecea0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#55 0x00007ffff399d856 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#56 0x00007ffff39a2b46 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#57 0x00005555556bded3 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffddb8) at /usr/src/debug/media-video/olive-9999/olive-9999/app/main.cpp:184
```
</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
Can you elaborate on what you mean by "undo"? It doesn't sound like you mean the "Undo" (Ctrl+Z) function, do you mean to say "delete" or "disconnect"?

**Comment by parona-source** [comment]
In the nodeview you can right click a node and in that  context menu i can "undo" it.

I originally got this when randomly selecting several nodes and clicking "undo". 

https://user-images.githubusercontent.com/46777059/112001867-03954900-8b28-11eb-88ce-0a29fe49ea93.mp4
