### ISSUE TITLE
Copying a clip with a transition crashes the application

### ISSUE THREAD

**Issue by feeef** [olive-editor/olive#198]
Copying a clip, on the timeline, that has a transition (cross dissolve) applied to it, crashes the application with a "Segmentation fault" error.

Tested on the alpha branch and got the same result with both "right click + copy" and the "Ctrl C" keyboard shortcut.

**Comment by eszlari** [comment]
I produced a backtrace for this crash:
```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00000000004ba232 in Transition::Transition (this=0x52d3c90, c=<optimized out>, s=<optimized out>, em=<optimized out>) at ../project/transition.cpp:32
32          length_ui_ele->set_frame_rate(parent_clip->sequence->frame_rate);
(gdb) bt
#0  0x00000000004ba232 in Transition::Transition (this=0x52d3c90, c=<optimized out>, s=<optimized out>, em=<optimized out>) at ../project/transition.cpp:32
#1  0x00000000004af379 in CrossDissolveTransition::CrossDissolveTransition (this=0x52d3c90, c=<optimized out>, s=<optimized out>, em=<optimized out>) at ../effects/internal/crossdissolvetransition.cpp:5
#2  0x00000000004ba41e in get_transition_from_meta (c=c@entry=0x490f450, s=s@entry=0x0, em=0x7fffd00086b8) at ../project/transition.cpp:69
#3  0x00000000004ba76d in create_transition (c=c@entry=0x490f450, s=s@entry=0x0, em=<optimized out>) at ../project/transition.cpp:83
#4  0x00000000004ba7cb in Transition::copy (this=0x2460b10, c=c@entry=0x490f450, s=s@entry=0x0) at ../project/transition.cpp:36
#5  0x0000000000467ecd in Clip::copy (this=this@entry=0x1e2e200, s=s@entry=0x0) at ../project/clip.cpp:69
#6  0x0000000000450ca9 in Timeline::copy (this=0xbbb240, del=<optimized out>) at ../panels/timeline.cpp:849
#7  0x00007ffff4779bb7 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5
#8  0x00007ffff525a392 in QAction::triggered(bool) () from /lib/libQt5Widgets.so.5
#9  0x00007ffff525c770 in QAction::activate(QAction::ActionEvent) () from /lib/libQt5Widgets.so.5
#10 0x00007ffff53c261a in ?? () from /lib/libQt5Widgets.so.5
#11 0x00007ffff53c979c in ?? () from /lib/libQt5Widgets.so.5
#12 0x00007ffff53ca856 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /lib/libQt5Widgets.so.5
#13 0x00007ffff529d0e8 in QWidget::event(QEvent*) () from /lib/libQt5Widgets.so.5
#14 0x00007ffff53ccc6b in QMenu::event(QEvent*) () from /lib/libQt5Widgets.so.5
#15 0x00007ffff526048c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#16 0x00007ffff5268780 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#17 0x00007ffff474e218 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#18 0x00007ffff5266afd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /lib/libQt5Widgets.so.5
#19 0x00007ffff52b6b20 in ?? () from /lib/libQt5Widgets.so.5
#20 0x00007ffff52b8fa3 in ?? () from /lib/libQt5Widgets.so.5
#21 0x00007ffff526048c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#22 0x00007ffff5267596 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#23 0x00007ffff474e218 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#24 0x00007ffff4c7c559 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/libQt5Gui.so.5
#25 0x00007ffff4c7e245 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/libQt5Gui.so.5
#26 0x00007ffff4c5aa0b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Gui.so.5
#27 0x00007fffeb50c8bb in ?? () from /lib/libQt5XcbQpa.so.5
#28 0x00007ffff474cb5a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#29 0x00007ffff53c755d in QMenu::exec(QPoint const&, QAction*) () from /lib/libQt5Widgets.so.5
#30 0x0000000000462945 in TimelineWidget::show_context_menu (this=0xcb5fe0, pos=...) at ../ui/timelinewidget.cpp:194
#31 0x00007ffff4779bb7 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5
#32 0x00007ffff52840a5 in QWidget::customContextMenuRequested(QPoint const&) () from /lib/libQt5Widgets.so.5
#33 0x00007ffff529dedd in QWidget::event(QEvent*) () from /lib/libQt5Widgets.so.5
#34 0x00007ffff526048c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#35 0x00007ffff52683e8 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#36 0x00007ffff474e218 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#37 0x00007ffff52b6864 in ?? () from /lib/libQt5Widgets.so.5
#38 0x00007ffff52b8fa3 in ?? () from /lib/libQt5Widgets.so.5
#39 0x00007ffff526048c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#40 0x00007ffff5267596 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#41 0x00007ffff474e218 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#42 0x00007ffff4c7c559 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/libQt5Gui.so.5
#43 0x00007ffff4c7e245 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/libQt5Gui.so.5
#44 0x00007ffff4c5aa0b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Gui.so.5
#45 0x00007fffeb50c8bb in ?? () from /lib/libQt5XcbQpa.so.5
#46 0x00007ffff474cb5a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#47 0x00007ffff47554f0 in QCoreApplication::exec() () from /lib/libQt5Core.so.5
#48 0x000000000042c1ef in main (argc=<optimized out>, argv=<optimized out>) at ../main.cpp:18
```
If you want to reproduce this yourself:
```
flatpak install flathub org.kde.Sdk//5.11
flatpak install flathub org.olivevideoeditor.Olive.Debug
flatpak run -d --command=sh org.olivevideoeditor.Olive
gdb olive-editor
(gdb) run
[trigger crash]
(gdb) bt
```
