### ISSUE TITLE
[EDIT] The program freezes while editing in the timeline 

### ISSUE THREAD

**Issue by JoseOlin** [olive-editor/olive#2184]
**Commit Hash**: 3bc53cef  

**Platform**. Linux Mint 20.3 (based on Ubuntu 20.04.5 LTS) 

**Summary**
The program freezes while editing in the timeline.

Apparently it happens after Zooming in on the timeline, but not every time.

It started to happen after version 2022 09 26 (9d54e24d). When I use that version the program behaves much more stable. Any version of the AppImage higher than that presents the same problem; I have tried 2022-11-01(c06d17cf) , 2023-02-13(41559576) and 2023-02-22(3bc53cef), all with the same behavior.

Is there anything that has changed after version 2022 09 26 (9d54e24d) that can help me locate the problem?

**Additional Information / Output**

No processor core shows busy, but when trying to close the window, the OS says it's not responding and offers to force quit or keep waiting.

I'm running the AppImage with gbd but it doesn't give me any indication of what the problem might be. Anyway I'm attaching the output in case you guys see anything relevant.

```
Reading symbols from /media/Ext4/Programs/Olive-editor/Olive_v23-02-22_3bc53cef.AppImage...`

(No debugging symbols found in /media/Ext4/Programs/Olive-editor/Olive_AppImage/Olive_v23-02-22_3bc53cef.AppImage)
Starting program: /media/Ext4/Programs/Olive-editor/Olive_AppImage/Olive_v23-02-22_3bc53cef.AppImage 
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 77335]
process 77324 is executing new program: /usr/bin/env
process 77324 is executing new program: /usr/bin/bash
[Detaching after fork from child process 77341]
[Detaching after fork from child process 77343]
[DEBUG] Extracting default OCIO config to "/home/user/.cache/olivevideoeditor.org/Olive/ocioconf"
[INFO] Using Qt version: 5.15.2
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
[INFO] Setting output audio device to default
[INFO] Setting input audio device to default
[DEBUG] Using graphics driver: Intel
[DEBUG] olive::ProjectLoadTask(0x3c05e50) took 414
[DEBUG] Selected node: olive::TransformDistortNode(0x7fff7c0492c0)
[DEBUG] Selected node: olive::TransformDistortNode(0x4023010)
[DEBUG] olive::ProjectSaveTask(0x45889f0) took 2
[DEBUG] Selected node: olive::TransformDistortNode(0x7fffc0035ec0)
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
[DEBUG] olive::ProjectSaveTask(0x4141c80) took 8
[DEBUG] Saved auto-recovery to: "/home/joseolin/.local/share/olivevideoeditor.org/Olive/autorecovery/{1e54c66b-4c32-4480-bcac-39c7cee64d8f}/1677469943.ove"
[DEBUG] Selected node: olive::TransformDistortNode(0x4168fc0)
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
[DEBUG] Selected node: olive::TransformDistortNode(0x41464c0)
[DEBUG] Selected node: olive::TransformDistortNode(0x3cb5700)
[WARNING] UpdateTextureFromNode called while playing
[DEBUG] olive::ProjectSaveTask(0x411bf10) took 5
[DEBUG] Saved auto-recovery to: "/home/joseolin/.local/share/olivevideoeditor.org/Olive/autorecovery/{1e54c66b-4c32-4480-bcac-39c7cee64d8f}/1677470123.ove"
[DEBUG] Selected node: olive::TransformDistortNode(0x41730f0)
```

**Comment by JoseOlin** [comment]
Hi guys.

I finally found a way to replicate the freezing, after going through some past issues, especially [this one](https://github.com/olive-editor/olive/issues/1569).

**Comment by itsmattkc** [comment]
That issue is over two years old and likely completely unrelated.

**Comment by JoseOlin** [comment]
Hello, thanks for the prompt response.

The way reported is my way of reproducing the problem: just adding a clip, pressing (and holding) the space bar and moving the playhead back and forth over the timeline (with left click pressed). 

Freezing occurs sometimes almost immediately, but other times after a few seconds.

In my case the freezing occur in all sessions (especially when there are a lot of short clips), and it's the reason why I can't use Olive on a regular basis.

**Comment by ThomasWilshaw** [comment]
I'm completeely unable to reproduce this on Windows, are you still experienceing this issue?

**Comment by JoseOlin** [comment]
> I'm completeely unable to reproduce this on Windows, are you still experienceing this issue?

Hi, @ThomasWilshaw! Yes, unfortunately it still happens. I just checked with the latest version (Sep 11 2023) and it happens almost immediately with some clips and around the 9th second in the gif I attached.

I tried with ogv files, because in LibreOffice I was having problems playing mp4 although it plays ogv files correctly, however in Olive it happens with both mp4 and ogv.

![Olive-freezing-playhead-moving](https://github.com/olive-editor/olive/assets/6277774/91faa509-ac5e-4421-af96-ff57ed40ff5f)

The last messages in the console before the freezing are:

<details><summary>Details</summary>

```
[INFO] Setting output audio device to default
[INFO] Setting input audio device to default
[DEBUG] Using graphics driver: Intel
[DEBUG] olive::ProjectLoadTask(0x40d2510) took 9
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
/tmp/.mount_Olive_ushmKN/AppRun: línea 8: 24850 Terminado (killed)      "$APPDIR/usr/bin/olive-editor" "$@"
```

</details> 


I remember that the versions that were installed with a .deb were much more stable. Any chance to incorporate the .deb back into the release files?

**Comment by ThomasWilshaw** [comment]
Can you try a clip with no audio (or just delete the audio from that clip)

**Comment by JoseOlin** [comment]
> Can you try a clip with no audio (or just delete the audio from that clip). Also are you able to provide a backtrace/run through a debugger?

Thanks for the suggestion, @ThomasWilshaw . Indeed, isolating the problem will be half the solution.

I did the test by unlinking the audio from the video of an mp4 in Olive and also re-encoding an mp4 without audio with QWinFF. Unfortunately, in both cases, freezing continues to occur.

**Comment by TechPersonYT** [comment]
With some effort I was able to reproduce a freeze by holding space and moving the playhead around wildly in a debug build. Here's the backtrace from GDB after I did Ctrl-C during the hang:

```
Thread 1 "AppRun" received signal SIGINT, Interrupt.
__futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=3600890, futex_word=0x7ffe9dffb910) at ./nptl/futex-internal.c:57
57	./nptl/futex-internal.c: No such file or directory.
(gdb) bt
#0  __futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=3600890, futex_word=0x7ffe9dffb910) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=128, abstime=0x0, clockid=0, expected=3600890, futex_word=0x7ffe9dffb910) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7ffe9dffb910, expected=3600890, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128)
    at ./nptl/futex-internal.c:139
#3  0x00007ffff2fee624 in __pthread_clockjoin_ex (threadid=140731549201984, thread_return=0x7fffffffc5c8, clockid=0, abstime=0x0, block=<optimized out>) at ./nptl/pthread_join_common.c:105
#4  0x00007ffff481b40d in PaUnixThread_Terminate () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libportaudio.so.2
#5  0x00007ffff480fc13 in RealStop () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libportaudio.so.2
#6  0x000000000050ff47 in olive::AudioManager::StopOutput (this=0x418ac10) at /opt/olive/app/audio/audiomanager.cpp:164
#7  0x0000000000837d34 in olive::ViewerWidget::PauseInternal (this=0x7fff38002a40) at /opt/olive/app/widget/viewer/viewer.cpp:1028
#8  0x0000000000832c3a in olive::ViewerWidget::TimeChangedEvent (this=0x7fff38002a40, time=...) at /opt/olive/app/widget/viewer/viewer.cpp:171
#9  0x00000000007e1020 in olive::TimeBasedWidget::PlayheadTimeChanged (this=0x7fff38002a40, time=...) at /opt/olive/app/widget/timebased/timebasedwidget.cpp:384
#10 0x00000000007e7fc1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<olive::core::rational const&>, void, void (olive::TimeBasedWidget::*)(olive::core::rational const&)>::call (
    f=(void (olive::TimeBasedWidget::*)(olive::TimeBasedWidget * const, const olive::core::rational &)) 0x7e0c04 <olive::TimeBasedWidget::PlayheadTimeChanged(olive::core::rational const&)>, 
    o=0x7fff38002a40, arg=0x7fffffffc9f0) at /usr/local/include/QtCore/qobjectdefs_impl.h:152
#11 0x00000000007e7755 in QtPrivate::FunctionPointer<void (olive::TimeBasedWidget::*)(olive::core::rational const&)>::call<QtPrivate::List<olive::core::rational const&>, void> (
    f=(void (olive::TimeBasedWidget::*)(olive::TimeBasedWidget * const, const olive::core::rational &)) 0x7e0c04 <olive::TimeBasedWidget::PlayheadTimeChanged(olive::core::rational const&)>, 
    o=0x7fff38002a40, arg=0x7fffffffc9f0) at /usr/local/include/QtCore/qobjectdefs_impl.h:185
#12 0x00000000007e69ad in QtPrivate::QSlotObject<void (olive::TimeBasedWidget::*)(olive::core::rational const&), QtPrivate::List<olive::core::rational const&>, void>::impl (which=1, 
    this_=0x2f8f1830, r=0x7fff38002a40, a=0x7fffffffc9f0, ret=0x0) at /usr/local/include/QtCore/qobjectdefs_impl.h:418
#13 0x00007ffff36a5e33 in void doActivate<false>(QObject*, int, void**) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#14 0x00000000004b0e1d in olive::ViewerOutput::PlayheadChanged (this=0x7ffef00173b0, _t1=...) at /opt/olive/build/app/libolive-editor_autogen/TZS4I5HN7D/moc_viewer.cpp:336
#15 0x00000000006169bb in olive::ViewerOutput::SetPlayhead (this=0x7ffef00173b0, t=...) at /opt/olive/app/node/output/viewer/viewer.cpp:329
#16 0x00000000008271b8 in olive::SeekableWidget::SeekToScenePoint (this=0x2cb9df10, scene=31) at /opt/olive/app/widget/timeruler/seekablewidget.cpp:403
#17 0x0000000000826266 in olive::SeekableWidget::mouseMoveEvent (this=0x2cb9df10, event=0x7fffffffd020) at /opt/olive/app/widget/timeruler/seekablewidget.cpp:218
#18 0x00007ffff4247326 in QWidget::event(QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff42f2d8e in QFrame::event(QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff453da3c in QGraphicsView::viewportEvent(QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff367171b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#22 0x00007ffff42076de in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff42100a8 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#24 0x00007ffff367199a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#25 0x00007ffff420f420 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#26 0x00007ffff42612cc in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff42643dc in QWidgetWindow::event(QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff42076ef in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff420fec8 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff367199a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#31 0x00007ffff3afcba3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Gui.so.5
#32 0x00007ffff3afe109 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Gui.so.5
#33 0x00007ffff3ad7e5c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Gui.so.5
#34 0x00007fffea4ff1ca in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () from /tmp/.mount_Olive-FtULaI/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#35 0x00007fffec91bd3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fffec971258 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fffec9193e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff36c77ee in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#39 0x00007ffff367070b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#40 0x00007ffff36781cc in QCoreApplication::exec() () from /tmp/.mount_Olive-FtULaI/usr/bin/../lib/libQt5Core.so.5
#41 0x000000000087e0fc in main (argc=1, argv=0x7fffffffdfd8) at /opt/olive/app/main.cpp:342
```

It looks to me like it's blocking on `AudioManager::StopOutput` while joining threads, but I'm new to debugging so take this with a grain of salt. I will try to investigate further once I have time.
