### ISSUE TITLE
Crash when cancelling export about 30% of the time on certain projects

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#576]
__Olive version:__  6c166a1a4e6068857c1daeb4f9bae034e6d06652
__Source:__ git
__Operating system:__ Ubuntu MATE 18.10, Windows 10
__CPU:__ i7-3770 or i5-6300HQ
__GPU:__ Intel i915 or NVidia Quadro FX 380

### Detailed Description

Some, but not all, of the time while clicking Cancel on an export with certain projects, Olive crashes with a `free(): corrupted unsorted chunks` error.

Completing the export does *not* crash, and produces a valid render, as far as I've seen.

### Steps to reproduce

1) Open attached project, [Backwards-issue.zip](https://github.com/olive-editor/olive/files/2915806/Backwards-issue.zip)
2) Right-click clip in Timeline, Speed/Duration, click Reverse, OK.
3) Re-save project (not sure if the reverse affects this or not, but this was the use case I was able to reproduce the crash most easily)
4) Export with default settings to a convenient directory
5) Cancel the export progress with the X button to the right of the progress bar (I usually cancelled around 10-30% completion)
6) **If no crash occurs**, go back to step 4
7) **If crash occurs**, observe error

Out of 12 cancelled exports in my testing, 4 crashes occurred. I saw the same issue on Windows and Linux with about the same ratio of reproducibility.

### Output log

Backtrace from gdb:

```
2019-02-28T15:47:39 [WARNING] "VID_20180815_223825.mp4" frame had no PTS value
2019-02-28T15:47:39 [WARNING] "VID_20180815_223825.mp4" frame had no PTS value
2019-02-28T15:47:40 [WARNING] QObject::startTimer: Timers cannot be started from another thread
free(): corrupted unsorted chunks

Thread 1 "olive-editor" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4a8e077 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4a6f535 in __GI_abort () at abort.c:79
#2  0x00007ffff4ad6516 in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff4bfac00 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff4add3aa in malloc_printerr
    (str=str@entry=0x7ffff4bfc980 "free(): corrupted unsorted chunks") at malloc.c:5336
#4  0x00007ffff4adf6e3 in _int_free
    (av=0x7ffff4c31c40 <main_arena>, p=0x55555690b6e0, have_lock=<optimized out>) at malloc.c:4304
#5  0x00007ffff593bb53 in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007ffff52993ec in QObject::~QObject() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff5939829 in QPlatformTextureList::~QPlatformTextureList() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007ffff5c36d2e in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff5c37a29 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff5c4eaf5 in QWidgetPrivate::syncBackingStore() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff5c66908 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5d6cf34 in QMainWindow::event(QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff5c284a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff5c2fae0 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff5269499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff526c48b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff52bbb23 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff2bc0c3e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff2bc0ed8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff2bc0f6c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff52bb143 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fffe2e48e51 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#23 0x00007ffff526816b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff5e1322d in QDialog::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x000055555566387a in OliveGlobal::open_export_dialog() ()
#26 0x000055555567d06d in OliveGlobal::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#27 0x00007ffff52926db in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff5c21ef2 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff5c24500 in QAction::activate(QAction::ActionEvent) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff5c24db4 in QAction::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff5c284a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff5c2fae0 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff5269499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff5699233 in QShortcutMap::dispatchEvent(QKeyEvent*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007ffff569930b in QShortcutMap::tryShortcut(QKeyEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#36 0x00007ffff564e866 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#37 0x00007ffff566acbd in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007ffff5670415 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#39 0x00007ffff564ab6b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#40 0x00007fffe2e48e5b in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#41 0x00007ffff526816b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff52702e2 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00005555555a834a in main ()
```

**Comment by itsmattkc** [comment]
48497ddafacfbd50d1da03c47b22eaa1d7b5bbfb should fix this.
