### ISSUE TITLE
Crash when opening project

### ISSUE THREAD

**Issue by eszlari** [olive-editor/olive#584]
When I try to open a project (given as an argument to the executable), Olive crashes:

```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00007ffff5dcf312 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
```

(Tested with flatpak & appimage)

**Comment by itsmattkc** [comment]
I'm guessing opening normally works fine?

**Comment by eszlari** [comment]
> I'm guessing opening normally works fine?

Yes.

**Comment by itsmattkc** [comment]
Is this any project file or just one?

**Comment by eszlari** [comment]
Every project I create (e.g. just one video file imported and added to the timeline).

**Comment by morrolinux** [comment]
Same here. Opening up a project crashes olive in the middle of loading. Not with all projects though. 
I created a crashtest.ove with one video track and a cut: opens up fine if program is running via "Open Project".
I was working on a bigger project file (around 100kb) featuring two video tracks, an image, a title with styling and transition, and it crashes out Olive when trying to open the same way.
here's the only output being logged:
```
2019-03-06T19:47:43 [WARNING] QApplication: invalid style override passed, ignoring it.
    Available styles: Breeze, Windows, Fusion ((null):0, (null))
2019-03-06T19:47:43 [WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
2019-03-06T19:47:43 [INFO] Initializing custom cursors ((null):0, (null))
2019-03-06T19:47:43 [INFO] Finished initializing custom cursors ((null):0, (null))
2019-03-06T19:47:43 [INFO] Initializing effects... ((null):0, (null))
2019-03-06T19:47:43 [INFO] Finished initializing effects ((null):0, (null))
2019-03-06T19:47:43 [WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))

2019-03-06T19:48:04 [INFO] Matched "video-2019-03-06_12.01.26.mp4" with absolute path ((null):0, (null))
2019-03-06T19:48:04 [INFO] Matched "video-2019-03-06_12.18.03.mp4" with absolute path ((null):0, (null))
2019-03-06T19:48:04 [INFO] Matched "../DeepinScreenshot_seleziona-area_20190306162118.png" with absolute path ((null):0, (null))

```

**Comment by morrolinux** [comment]
Actualy I just found out what line of the project makes it crash on load. I'm not sure if it has something to do with this issue anymore, but here it is:

```
...
            <clip id="44" enabled="1" name="video-2019-03-06_12.01.26.mp4" clipin="6418" in="3610" out="3686" track="-1" r="128" g="128" b="192" autoscale="0" speed="1.0000000000" maintainpitch="0" reverse="0" type="0" media="1" stream="0">
                <linked>
                    <link id="43"/>
                </linked>

                <opening shared="37"/>       <-- THIS LINE makes it crash (line 500 on the project)

                <effect name="Distort/Transform" enabled="1">
...
```
Removing the incriminated line recovers the project.
I'm attaching the project file.
[pixeluvo-demo.ove.zip](https://github.com/olive-editor/olive/files/2937888/pixeluvo-demo.ove.zip)

**Comment by morrolinux** [comment]
looking at the exported video I think line 500 (which I removed to recover the project) was taking part in a cross dissolve, since now the clip just fades to black and then a new one appears

**Comment by itsmattkc** [comment]
@morrolinux Indeed, 3ca935d46dd7ab0a274a42a791c1a6349270f018 should fix your issue, though I'm not sure it's related to @eszlari's

**Comment by morrolinux** [comment]
@itsmattkc Thanks man! awesome project btw

**Comment by itsmattkc** [comment]
@eszlari Does the latest commit fix this issue?

**Comment by eszlari** [comment]
> @eszlari Does the latest commit fix this issue?

Unfortunately, no.

**Comment by itsmattkc** [comment]
@eszlari Can you provide a full GDB backtrace?

**Comment by eszlari** [comment]
```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00007ffff5dce312 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff5dce312 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff5da51ac in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff5da5954 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff5df1ed4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff5df298e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff5d95651 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff5d9cc80 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff518ef79 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5795be6 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007ffff5795e6d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007ffff577018b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#11 0x00007fffeff744fa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#12 0x00007ffff3ea161e in g_main_dispatch (context=0x7fffe8004ff0) at ../glib/gmain.c:3182
#13 g_main_context_dispatch (context=context@entry=0x7fffe8004ff0) at ../glib/gmain.c:3847
#14 0x00007ffff3ea18b8 in g_main_context_iterate (context=context@entry=0x7fffe8004ff0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3920
#15 0x00007ffff3ea1950 in g_main_context_iteration (context=0x7fffe8004ff0, may_block=1) at ../glib/gmain.c:3981
#16 0x00007ffff51e3873 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff518dc4b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff5195db2 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00005555555aec0a in main (argc=<optimized out>, argv=<optimized out>) at ../main.cpp:147

```

**Comment by itsmattkc** [comment]
Try 928502ec5b73bc6f482afd54f0fbcb6e7e59066c

**Comment by eszlari** [comment]
It's fixed now!
