### ISSUE TITLE
Segfault when skimming over footage

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#603]
Olive version: 464ce74
Source: Git
Operating system: Antergos 
CPU: i7-8550U 
RAM: 16GB
GPU: GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 418.43
Window Server: X11

### Detailed Description

When skimming over footage with the playhead, Olive will crash.

I have run Olive from the Intel iGPU, (using Wayland) and there was no crash.

### Steps to reproduce

1.  Import Footage
2. Add footage to timeline
3.  Skim over footage rapidly in timeline

### GDB Backtrace

```
Thread 4 "RenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2395700 (LWP 373)]
0x00007fffe32897d0 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
(gdb) bt
#0  0x00007fffe32897d0 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#1  0x00007fffe2d52576 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#2  0x00007fffe2d5d15a in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#3  0x00007fffe2ecc6d3 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#4  0x00007fffe2e9a1f4 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#5  0x00007fffe2e9bb17 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#6  0x00007fffe2eb66c6 in ?? () from /usr/lib/libnvidia-glcore.so.418.43
#7  0x00007ffff5b12d2e in ?? () from /usr/lib/libQt5Gui.so.5
#8  0x00007ffff5b13df2 in QOpenGLTexture::setData(QOpenGLTexture::PixelFormat, QOpenGLTexture::PixelType, void const*, QOpenGLPixelTransferOptions const*) () from /usr/lib/libQt5Gui.so.5
#9  0x00005555555e746d in Clip::Retrieve() ()
#10 0x0000555555668cbd in compose_sequence(ComposeSequenceParams&) ()
#11 0x000055555566acfe in RenderThread::paint() ()
#12 0x000055555566b274 in RenderThread::run() ()
#13 0x00007ffff521896c in ?? () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff482ea9d in start_thread () from /usr/lib/libpthread.so.0
#15 0x00007ffff4cceb23 in clone () from /usr/lib/libc.so.6
```

### Output Log from Olive: (replaced directory with **my folder**)

```
2019-03-06T17:24:15 [DEBUG] using qt5ct plugin
2019-03-06T17:24:15 [WARNING] QApplication: invalid style override passed, ignoring it.
    Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, qt5ct-style, Windows, Fusion
2019-03-06T17:24:15 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
2019-03-06T17:24:15 [INFO] Initializing custom cursors
2019-03-06T17:24:15 [INFO] Finished initializing custom cursors
2019-03-06T17:24:16 [INFO] Initializing effects...
2019-03-06T17:24:16 [INFO] Finished initializing effects
2019-03-06T17:24:16 [DEBUG] D-Bus global menu: no
2019-03-06T17:24:16 [DEBUG] palette support is disabled
2019-03-06T17:24:16 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/**my folder**/DSCF4971_prores.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf58.20.100
    comment         : FUJIFILM DIGITAL CAMERA X-T3
    comment-eng     : FUJIFILM DIGITAL CAMERA X-T3
  Duration: 00:00:51.00, start: 0.000000, bitrate: 214992 kb/s
    Stream #0:0(eng): Video: prores (apch / 0x68637061), yuv422p10le(tv, smpte170m/bt709/smpte170m, progressive), 3840x2160, 213452 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 prores_ks
      timecode        : 02:28:53:19
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : TimeCodeHandler
      timecode        : 02:28:53:19
2019-03-06T17:25:28 [ERROR] Unsupported codec in stream 2 of file "DSCF4971_prores.mov"
[swscaler @ 0x7f880a1131c0] Warning: data is not aligned! This can lead to a speed loss
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/**my folder**/DSCF4971_prores.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf58.20.100
    comment         : FUJIFILM DIGITAL CAMERA X-T3
    comment-eng     : FUJIFILM DIGITAL CAMERA X-T3
  Duration: 00:00:51.00, start: 0.000000, bitrate: 214992 kb/s
    Stream #0:0(eng): Video: prores (apch / 0x68637061), yuv422p10le(tv, smpte170m/bt709/smpte170m, progressive), 3840x2160, 213452 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 prores_ks
      timecode        : 02:28:53:19
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : TimeCodeHandler
      timecode        : 02:28:53:19
2019-03-06T17:25:30 [INFO] Clip opened on track 0 (took 53 ms)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/**my folder**/DSCF4971_prores.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf58.20.100
    comment         : FUJIFILM DIGITAL CAMERA X-T3
    comment-eng     : FUJIFILM DIGITAL CAMERA X-T3
  Duration: 00:00:51.00, start: 0.000000, bitrate: 214992 kb/s
    Stream #0:0(eng): Video: prores (apch / 0x68637061), yuv422p10le(tv, smpte170m/bt709/smpte170m, progressive), 3840x2160, 213452 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 prores_ks
      timecode        : 02:28:53:19
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : TimeCodeHandler
      timecode        : 02:28:53:19
2019-03-06T17:25:30 [INFO] Clip opened on track -1 (took 45 ms)
Segmentation fault (core dumped)

```

**Comment by itsmattkc** [comment]
Confirmed fixed in 0f7425d47318abe1a4df9a8ae1b42b211bdbc253
