### ISSUE TITLE
Crash when importing many clips and using footage viewer

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#659]
### System Information

Olive version: 1da4a31
Source: GIT
Operating system: Arch Linux
CPU: i7-8550U
GPU: GeForce MX150 NVIDIA 418.43 (Nvidia Prime with Intel UHD 620)
Driver: Nvidia v: 418.43

### Detailed Description

When importing many (I used 10 clips) from a Panasonic GH5 Olive imports them fine, but when the user quickly previews footage- or double clicks another clip to preview Olive crashes.

### Output Log (omitted media load metadata)

```
[Thread 0x7fffba08b700 (LWP 2306) exited]
[New Thread 0x7fffba08b700 (LWP 2314)]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fffa0000900] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fffa0000900] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
[New Thread 0x7fff967fc700 (LWP 2315)]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fff80009240] st: 0 edit list: 1 Missing key frame while searching for timestamp: 3600
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fff80009240] st: 0 edit list 1 Cannot find an index entry before timestamp: 3600.
2019-03-21T15:59:00 [FATAL] QThread: Destroyed while thread is still running

Thread 1 "olive-editor" received signal SIGABRT, Aborted.
```

### GDB/CDB Backtrace (for crashes)

```
Thread 1 "olive-editor" received signal SIGABRT, Aborted.
0x00007ffff49fed7f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff49fed7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff49e9672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff4fd07fc in QMessageLogger::fatal(char const*, ...) const ()
   from /usr/lib/libQt5Core.so.5
#3  0x00007ffff4fd1055 in ?? () from /usr/lib/libQt5Core.so.5
#4  0x00005555555e8cd4 in Clip::~Clip() ()
#5  0x00005555555e61d7 in QVector<std::shared_ptr<Clip> >::freeData(QTypedArrayData<std::shared_ptr<Clip> >*) [clone .isra.32] ()
#6  0x00005555555e6301 in Sequence::~Sequence() ()
#7  0x00005555555c47a2 in Viewer::clean_created_seq() ()
#8  0x00005555555c6095 in Viewer::set_media(Media*) ()
#9  0x0000555555644204 in SourcesCommon::OpenSelectedMediaInMediaViewer(Media*) ()
#10 0x0000555555644703 in SourcesCommon::mouseDoubleClickEvent(QList<QModelIndex> const&) ()
#11 0x00005555555d3801 in SourceTable::mouseDoubleClickEvent(QMouseEvent*) ()
#12 0x00007ffff5d8778f in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff5e2e86f in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff5fa950c in QAbstractItemView::viewportEvent(QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff6013c0c in QTreeView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff51c6b0b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff5d45e14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007ffff5d4d839 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff51c6df9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff5d4cb18 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool)
    () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff5da1f53 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff5da5047 in ?? () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5d45e24 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff5d4d5f1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff51c6df9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff574fa50 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#27 0x00007ffff5750f16 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#28 0x00007ffff572a75c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#29 0x00007fffec0039ac in ?? () from /usr/lib/libQt5XcbQpa.so.5
#30 0x00007fffef2027bf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#31 0x00007fffef204739 in ?? () from /usr/lib/libglib-2.0.so.0
#32 0x00007fffef20477e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff521cc99 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff51c5a8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ffff51cdde6 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#36 0x00005555555a7ceb in main ()
```

**Comment by BrimsonBhin** [comment]
I am also getting this bug on Windows 10 as well (same version too)

### Steps to reproduce

1. Import media in any way possible and try to drag it to the timeline window
2. Olive "locks itself" and crashes

I believe this bug was inherited from the recent exportthread restructure a few hours ago.

**Comment by alcomposer** [comment]
I get exactly the same crash (with same backtrace) if I only import one clip by double click the media clip a few times in a row.

I don't think this has anything to do with how many clips one imports. (but having multiple clips encourages a user to double click multiple times - in order to view the different media)

**Comment by itsmattkc** [comment]
Is this fixed in 067eec0b90aea3e43c26f972177c21802d369b7f?

**Comment by BrimsonBhin** [comment]
@itsmattkc Footage viewer was fixed, but importing **explicitly through dragging was not**. However, I did found a workaround that did not result in a crash..

1. Right-click the project window
2. Create a new sequence through the context menu
3. Things should work as it should

I believe that the crash was happening with sequence creation after the user drags their media into the timeline with no sequence whatsoever.

**Comment by itsmattkc** [comment]
This issue appears to be about two separate issues.

The OP appears to be about rapidly double-clicking footage in the Project panel causing a crash (which should be fixed in 22b208143be1f50078c61dbb977826057946f174).

Your issue sounds separate, you're saying you can't drag media into the Timeline panel without having created a Sequence in advance? Is that dragging from the Project panel or dragging from a file manager outside Olive?

**Comment by BrimsonBhin** [comment]
@itsmattkc Ah sorry about that. I will open a new issue addressing the issue.

Yes, I can't drag media into the Timeline panel without having created a Sequence in advance (otherwise, it would crash. Dragging from either a file manager or project panel, does not matter

**Comment by alcomposer** [comment]
@itsmattkc yes it is fixed on my end.
