### ISSUE TITLE
Random Crash in Timeline using Editing Tools

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#809]
### System Information
**Olive version:**  [659502fd]
**Source:** [node editor branch]
**Operating system:** [Antergos]
**CPU:** [Quad Core Intel Core i7-8550U]
**RAM:** [16 GB]
**GPU:** [GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 418.56 ]

### Detailed Description
[random crash when using editing tools in timeline]

### Steps to reproduce

[Edit media in timeline with razor, slip etc tool]

### GDB/CDB Backtrace (for crashes)
```
Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00005555556a3da4 in Node::Now() ()
(gdb) bt
#0  0x00005555556a3da4 in Node::Now() ()
#1  0x000055555567b1ee in EffectUI::UpdateFromEffect() ()
#2  0x00005555555c2f05 in EffectControls::update_keyframes() ()
#3  0x000055555569c8d4 in EffectsPanel::Load() ()
#4  0x000055555569cbe1 in EffectsPanel::SetClips() ()
#5  0x00005555555f8749 in update_ui(bool) ()
#6  0x0000555555693a88 in TimelineView::mouseReleaseEvent(QMouseEvent*) ()
#7  0x00007ffff5c7dc28 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff5c3ce24 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff5c44839 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff50bddf9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#11 0x00007ffff5c43b18 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff5c98f53 in ?? () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff5c9c047 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff5c3ce24 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff5c445f1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff50bddf9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#17 0x00007ffff5646aae in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#18 0x00007ffff5647f16 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#19 0x00007ffff562175c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#20 0x00007fffeb9e19ac in ?? () from /usr/lib/libQt5XcbQpa.so.5
#21 0x00007fffeec377bf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#22 0x00007fffeec39739 in ?? () from /usr/lib/libglib-2.0.so.0
#23 0x00007fffeec3977e in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff5113c99 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff50bca8c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff50c4de6 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#27 0x00005555555b30e7 in main ()

```

**Comment by itsmattkc** [comment]
I appreciate the crash report, however these functions have already changed a bit so we'll have to see as things develop
